In [2]:
import pandas as pd 
import numpy as np

In [3]:
data = pd.read_csv(
    r"D:\data-science-journey\Data_Science\Data\Student_data.csv", 
)

data.head()

,StudentID,Name,City,Math,Science,English,Computer,Percentage
0,1,Aarav Sharma,Ahmedabad,78,82,75,88,80.75
1,2,Diya Patel,Surat,91,89,94,96,92.50
2,3,Krish Verma,Vadodara,67,71,73,69,70.00
3,4,Ananya Singh,Rajkot,85,88,84,90,86.75
4,5,Rohan Mehta,Mumbai,76,74,79,81,77.50

In [4]:
data.head()

,StudentID,Name,City,Math,Science,English,Computer,Percentage
0,1,Aarav Sharma,Ahmedabad,78,82,75,88,80.75
1,2,Diya Patel,Surat,91,89,94,96,92.50
2,3,Krish Verma,Vadodara,67,71,73,69,70.00
3,4,Ananya Singh,Rajkot,85,88,84,90,86.75
4,5,Rohan Mehta,Mumbai,76,74,79,81,77.50

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   205 non-null    int64
 1   Name        205 non-null    object
 2   City        205 non-null    object
 3   Math        205 non-null    int64
 4   Science     205 non-null    int64
 5   English     205 non-null    int64
 6   Computer    205 non-null    int64
 7   Percentage  205 non-null    float64
dtypes: float64(1), int64(5), object(2)
memory usage: 12.9+ KB

In [6]:
data.describe()

        StudentID        Math     Science     English    Computer  Percentage
count  205.000000  205.000000  205.000000  205.000000  205.000000  205.000000
mean   103.000000   82.673171   84.117073   82.541463   85.731707   83.765854
std     59.322565    9.457620    9.304540    9.654547    9.272097    9.385406
min      1.000000   65.000000   66.000000   65.000000   69.000000   66.750000
25%     52.000000   75.000000   76.000000   74.000000   79.000000   76.000000
50%    103.000000   84.000000   85.000000   83.000000   87.000000   84.750000
75%    154.000000   91.000000   92.000000   91.000000   94.000000   91.750000
max    205.000000   98.000000   99.000000   99.000000  100.000000   98.500000

In [7]:

data.columns
data.shape

(205, 8)

In [8]:
data[['Name']]

             Name
0    Aarav Sharma
1      Diya Patel
2     Krish Verma
3    Ananya Singh
4     Rohan Mehta
..            ...
200    Parag Shah
201   Diya Kapoor
202   Rajiv Kumar
203    Kiara Jain
204     Het Patel

[205 rows x 1 columns]

In [9]:
data.loc[0,'City']  # lock the value by Col_lable

'Ahmedabad'

In [10]:
data.iloc[0,2] # lock the value by index

'Ahmedabad'

In [11]:
data.isnull().sum()

StudentID     0
Name          0
City          0
Math          0
Science       0
English       0
Computer      0
Percentage    0
dtype: int64

In [12]:
data.drop_duplicates()

,StudentID,Name,City,Math,Science,English,Computer,Percentage
0,1,Aarav Sharma,Ahmedabad,78,82,75,88,80.75
1,2,Diya Patel,Surat,91,89,94,96,92.50
2,3,Krish Verma,Vadodara,67,71,73,69,70.00
3,4,Ananya Singh,Rajkot,85,88,84,90,86.75
4,5,Rohan Mehta,Mumbai,76,74,79,81,77.50
...,...,...,...,...,...,...,...,...
200,201,Parag Shah,Vadodara,76,78,75,79,77.00
201,202,Diya Kapoor,Jaipur,93,95,92,96,94.00
202,203,Rajiv Kumar,Patna,68,70,67,71,69.00
203,204,Kiara Jain,Indore,87,89,88,90,88.50
204,205,Het Patel,Ahmedabad,80,82,79,83,81.00

In [13]:

data["Math"] = data["Math"].astype(int)
data["Maths_Topper"] = data["Math"].apply(
    lambda x: "weak" if x <= 60 else "avg" if x <= 80 else "topper"
)
data

,StudentID,Name,City,Math,Science,English,Computer,Percentage,Maths_Topper
0,1,Aarav Sharma,Ahmedabad,78,82,75,88,80.75,avg
1,2,Diya Patel,Surat,91,89,94,96,92.50,topper
2,3,Krish Verma,Vadodara,67,71,73,69,70.00,avg
3,4,Ananya Singh,Rajkot,85,88,84,90,86.75,topper
4,5,Rohan Mehta,Mumbai,76,74,79,81,77.50,avg
...,...,...,...,...,...,...,...,...,...
200,201,Parag Shah,Vadodara,76,78,75,79,77.00,avg
201,202,Diya Kapoor,Jaipur,93,95,92,96,94.00,topper
202,203,Rajiv Kumar,Patna,68,70,67,71,69.00,avg
203,204,Kiara Jain,Indore,87,89,88,90,88.50,topper
204,205,Het Patel,Ahmedabad,80,82,79,83,81.00,avg

# Data Transformation

In [14]:
data.sort_values(["Math"])

,StudentID,Name,City,Math,Science,English,Computer,Percentage,Maths_Topper
14,15,Rajat Kumar,Patna,65,68,66,70,67.25,avg
50,51,Vivek Sharma,Patna,65,66,68,70,67.25,avg
136,137,Sahil Mehta,Surat,65,67,66,69,66.75,avg
30,31,Ritesh Singh,Patna,66,67,69,71,68.25,avg
110,111,Harsh Mehta,Rajkot,66,68,67,70,67.75,avg
...,...,...,...,...,...,...,...,...,...
199,200,Tanisha Sharma,Delhi,97,99,96,100,98.00,topper
183,184,Priyanka Mehta,Mumbai,97,98,96,99,97.50,topper
135,136,Muskaan Sharma,Jaipur,98,97,99,100,98.50,topper
167,168,Riddhi Das,Kolkata,98,99,97,100,98.50,topper
191,192,Ayushi Singh,Delhi,98,97,99,100,98.50,topper

In [15]:
data.rename(columns = {"Math" : "Maths"} ,inplace=True)
data

,StudentID,Name,City,Maths,Science,English,Computer,Percentage,Maths_Topper
0,1,Aarav Sharma,Ahmedabad,78,82,75,88,80.75,avg
1,2,Diya Patel,Surat,91,89,94,96,92.50,topper
2,3,Krish Verma,Vadodara,67,71,73,69,70.00,avg
3,4,Ananya Singh,Rajkot,85,88,84,90,86.75,topper
4,5,Rohan Mehta,Mumbai,76,74,79,81,77.50,avg
...,...,...,...,...,...,...,...,...,...
200,201,Parag Shah,Vadodara,76,78,75,79,77.00,avg
201,202,Diya Kapoor,Jaipur,93,95,92,96,94.00,topper
202,203,Rajiv Kumar,Patna,68,70,67,71,69.00,avg
203,204,Kiara Jain,Indore,87,89,88,90,88.50,topper
204,205,Het Patel,Ahmedabad,80,82,79,83,81.00,avg

# MELT

In [16]:
data.melt(id_vars=["Name"],value_vars=["Maths","Science","English"],var_name="Subject",value_name="Scrore")

             Name  Subject  Scrore
0    Aarav Sharma    Maths      78
1      Diya Patel    Maths      91
2     Krish Verma    Maths      67
3    Ananya Singh    Maths      85
4     Rohan Mehta    Maths      76
..            ...      ...     ...
610    Parag Shah  English      75
611   Diya Kapoor  English      92
612   Rajiv Kumar  English      67
613    Kiara Jain  English      88
614     Het Patel  English      79

[615 rows x 3 columns]

# Joins

In [17]:
data.groupby("City")["Maths"].mean()

City
Ahmedabad     78.413793
Amritsar      86.000000
Bangalore     91.750000
Bhopal        82.000000
Chandigarh    96.000000
Chennai       84.333333
Delhi         85.826087
Hyderabad     89.000000
Indore        83.000000
Jaipur        92.285714
Kanpur        75.300000
Kochi         90.400000
Kolkata       91.437500
Lucknow       83.000000
Mumbai        84.769231
Nagpur        87.000000
Patna         71.153846
Pune          81.000000
Rajkot        79.538462
Surat         77.941176
Vadodara      77.833333
Name: Maths, dtype: float64

In [18]:
data.groupby(["City","Maths_Topper"])["Percentage"].agg( avg_score="mean", max_salary="max", sum_salary="sum")

                         avg_score  max_salary  sum_salary
City       Maths_Topper
Ahmedabad  avg           77.154762       81.00     1620.25
           topper        85.625000       93.75      685.00
Amritsar   avg           79.000000       79.00       79.00
           topper        95.000000       95.00       95.00
Bangalore  topper        93.062500       96.00      744.50
Bhopal     topper        82.750000       82.75       82.75
Chandigarh topper        96.500000       96.50       96.50
Chennai    avg           78.000000       78.00       78.00
           topper        89.875000       90.25      179.75
Delhi      avg           70.750000       74.75      495.25
           topper        93.656250       98.50     1498.50
Hyderabad  topper        90.500000       94.75      181.00
Indore     avg           71.562500       75.50      286.25
           topper        89.225000       97.50      892.25
Jaipur     avg           81.000000       81.00       81.00
           topper        94.153846       98.50     1224.00
Kanpur     avg           69.625000       72.00      417.75
           topper        86.187500       89.50      344.75
Kochi      topper        91.850000       94.50      459.25
Kolkata    topper        92.593750       98.50     1481.50
Lucknow    avg           76.000000       78.25      152.00
           topper        91.250000       95.75      182.50
Mumbai     avg           74.437500       77.50      297.75
           topper        91.055556       97.50      819.50
Nagpur     topper        88.000000       88.00       88.00
Patna      avg           70.181818       78.00      772.00
           topper        84.625000       87.50      169.25
Pune       avg           77.833333       80.00      233.50
           topper        94.250000       94.25       94.25
Rajkot     avg           75.041667       80.75      450.25
           topper        85.214286       91.75      596.50
Surat      avg           71.031250       80.75      568.25
           topper        86.555556       92.50      779.00
Vadodara   avg           76.875000       81.00      768.75
           topper        89.125000       95.50      178.25