In [ ]:
import pandas as pd 
import numpy as np

In [18]:
data = pd.read_csv(
    r"D:\data-science-journey\Data_Science\Data\Student_data.csv", 
)

data.head()
attendance = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Attendance": [92, 85, 96, 78]
})

In [ ]:
data.info()

In [ ]:
data.describe()

In [ ]:

data.columns
data.shape

In [ ]:
data[['Name']]

In [ ]:
data.loc[0,'City']  # lock the value by Col_lable

In [ ]:
data.iloc[0,2] # lock the value by index

In [ ]:
data.isnull().sum()

In [ ]:
data.drop_duplicates()

In [ ]:

data["Math"] = data["Math"].astype(int)
data["Maths_Topper"] = data["Math"].apply(
    lambda x: "weak" if x <= 60 else "avg" if x <= 80 else "topper"
)
data

# Data Transformation

In [ ]:
data.sort_values(["Math"])

In [ ]:
data.rename(columns = {"Math" : "Maths"} ,inplace=True)
data

# MELT

In [16]:
df_melted = data.melt(
    id_vars=["StudentID", "Name", "City"],
    value_vars=["Maths", "Science", "English", "Computer"],
    var_name="Subject",
    value_name="Marks"
)

df_melted

     StudentID          Name       City   Subject  Marks
0            1  Aarav Sharma  Ahmedabad     Maths     78
1            2    Diya Patel      Surat     Maths     91
2            3   Krish Verma   Vadodara     Maths     67
3            4  Ananya Singh     Rajkot     Maths     85
4            5   Rohan Mehta     Mumbai     Maths     76
..         ...           ...        ...       ...    ...
815        201    Parag Shah   Vadodara  Computer     79
816        202   Diya Kapoor     Jaipur  Computer     96
817        203   Rajiv Kumar      Patna  Computer     71
818        204    Kiara Jain     Indore  Computer     90
819        205     Het Patel  Ahmedabad  Computer     83

[820 rows x 5 columns]

In [ ]:
df_wide = df_melted.pivot(
    index=["StudentID", "Name", "City"],
    columns="Subject",
    values="Marks"
).reset_index()

In [ ]:
data.melt(id_vars=["Name"],value_vars=["Maths","Science","English"],var_name="Subject",value_name="Scrore")

# Joins

In [ ]:
data.groupby(["City","Maths_Topper"])["Percentage"].agg( avg_score="mean", max_salary="max", sum_salary="sum")

In [20]:
df_merged = data.merge(
    attendance,
    on="StudentID",
    how="inner"
)
df_merged

,StudentID,Name,City,Math,Science,English,Computer,Percentage,Attendance
0,101,Aarohi Patel,Ahmedabad,84,85,83,87,84.75,92
1,102,Yuvraj Singh,Delhi,72,74,71,75,73.00,85
2,103,Sanjana Mehra,Jaipur,95,96,94,98,95.75,96
3,104,Parthiv Shah,Surat,68,70,69,71,69.50,78

In [21]:
data.merge(
    attendance,
    on="StudentID",
    how="outer"
)

,StudentID,Name,City,Math,Science,English,Computer,Percentage,Attendance
0,1,Aarav Sharma,Ahmedabad,78,82,75,88,80.75,NaN
1,2,Diya Patel,Surat,91,89,94,96,92.50,NaN
2,3,Krish Verma,Vadodara,67,71,73,69,70.00,NaN
3,4,Ananya Singh,Rajkot,85,88,84,90,86.75,NaN
4,5,Rohan Mehta,Mumbai,76,74,79,81,77.50,NaN
...,...,...,...,...,...,...,...,...,...
200,201,Parag Shah,Vadodara,76,78,75,79,77.00,NaN
201,202,Diya Kapoor,Jaipur,93,95,92,96,94.00,NaN
202,203,Rajiv Kumar,Patna,68,70,67,71,69.00,NaN
203,204,Kiara Jain,Indore,87,89,88,90,88.50,NaN
204,205,Het Patel,Ahmedabad,80,82,79,83,81.00,NaN