# Section B: Handling Missing Values

In [65]:
import pandas as pd

In [66]:
df = pd.read_csv(r"D:\data-science-journey\Data_Science\Data\Flight_Booking_Advanced_Dirty_Dataset_5500_Records.csv")

In [67]:
# Count null values in CustomerName and EmailID ,MobileNo,FlightDate,SourceCity ,DestinationCity
df[['CustomerName', 'EmailID','MobileNo','FlightDate','SourceCity','DestinationCity']].isnull().sum()

CustomerName       934
EmailID            535
MobileNo           521
FlightDate         530
SourceCity         555
DestinationCity    543
dtype: int64

In [68]:
# Display rows where EmailID is missing. 
df[df['EmailID'].isnull()]

,BookingID,BookingDate,CustomerID,CustomerName,Gender,Age,MobileNo,EmailID,City,Country,...,ArrivalTime,SeatClass,SeatNumber,PNRNumber,TicketPrice,TaxAmount,TotalAmount,PaymentMode,PaymentStatus,BookingStatus
4,1496,2025-06-25,CUST001496,Tanmayi Apte,Female,58.0,5194803805.0,NaN,Imphal,UK,...,14:45,NaN,37D,PNR9053659,69585,3479.25,73064.25,Credit Card,Refunded,Waiting
20,2452,2025-07-15,CUST002452,Aishani Raman,Female,39.0,5958976887.0,NaN,Patiala,UAE,...,08:45,First Class,39B,PNR6877833,66445,3322.25,69767.25,Credit Card,Paid,Confirmed
30,317,2026-05-09,CUST000317,NaN,Female,53.0,7187846166.0,NaN,Ahmednagar,UK,...,02:30,Economy,41A,PNR9757413,2880,144.00,3024.00,Credit Card,Refunded,Confirmed
48,3771,2025-07-08,CUST003771,Rajata Hegde,Male,58.0,8632401011.0,NaN,Mysore,UAE,...,21:45,First Class,41C,PNR9558494,36179,1808.95,37987.95,Net Banking,Paid,Waiting
57,3256,2026-04-09,CUST003256,NaN,Female,46.0,4348034097.0,NaN,Surendranagar Dudhrej,Thailand,...,17:15,Business,41D,NaN,73030,3651.50,76681.50,Credit Card,Pending,Confirmed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5452,3485,2025-11-23,CUST003485,NaN,Female,Unknown,NaN,NaN,Phusro,India,...,08:45,First Class,8F,PNR2335246,60892,3044.60,63936.60,Credit Card,Pending,Confirmed
5455,4609,2026-02-17,CUST004609,Varenya Manda,Male,72.0,8860590132.0,NaN,Thoothukudi,Singapore,...,01:15,NaN,8F,PNR2511197,62171,3108.55,65279.55,Net Banking,Paid,Waiting
5467,3749,2025-06-25,CUST003749,Girish Basak,Male,74.0,2791971017.0,NaN,Parbhani,India,...,08:30,Premium Economy,29E,PNR3659634,0,1198.70,25172.70,Credit Card,Pending,Confirmed
5475,1274,2025-09-12,CUST001274,Reyansh Shah,Female,67.0,98765,NaN,Rajahmundry,UAE,...,11:15,First Class,23E,PNR5899016,32074,1603.70,33677.70,Debit Card,Pending,Cancelled
5481,4468,2025-08-19,CUST004468,Harinakshi Bains,Male,58.0,9717860293.0,NaN,Hospet,UAE,...,17:15,Economy,45E,PNR9750886,33021,1651.05,34672.05,Net Banking,Pending,Cancelled

In [69]:
# Replace missing EmailID with "Not Available"
# df['EmailID'] = df['EmailID'].fillna('Not Available')

In [70]:
# Replace missing MobileNo with "0000000000".
df['MobileNo'] = df['MobileNo'].fillna(0000000000)

In [71]:
# .Replace missing Age with average age. 
# df['Age'] = df['Age'].fillna(df['Age'].mean())

In [72]:
# .Replace missing SourceCity with "Unknown". 
df['SourceCity'] = df['SourceCity'].fillna('Unknown')

In [73]:
# .Replace missing DestinationCity with "Unknown". 
df['DestinationCity'] = df['DestinationCity'].fillna('Unknown')

In [74]:
# Replace missing FlightDate with current date
from datetime import date

today = date.today()
print(today)  
df['FlightDate'] = df['FlightDate'].fillna(today)

2026-09-07

In [75]:
# .Remove rows containing missing CustomerName. 
df['CustomerName'] = df['CustomerName'].dropna()

In [76]:
# Remove rows containing missing EmailID. 
df['EmailID'] = df['EmailID'].dropna()
df['EmailID'].count()

np.int64(4965)

In [77]:
# Display columns with at least 10% missing values
ten_per=df.isnull().mean().round(3)*100
col_name =ten_per[ten_per >= 10]
df[col_name.index]

           CustomerName   Age    SeatClass PaymentStatus
0      Bahadurjit Swamy  48.0  First Class       Pending
1                   NaN  33.0      Economy      Refunded
2             Diya Goel  30.0     Business       Pending
3           Omya Varkey  48.0  First Class       Pending
4          Tanmayi Apte  58.0          NaN      Refunded
...                 ...   ...          ...           ...
5495       Gayathri Ram  39.0      Economy      Refunded
5496         Veda Reddy  63.0     Business       Pending
5497           Max Natt  52.0      Economy          Paid
5498  Rachana Sabharwal  32.0     Business          Paid
5499        Waida Yadav  68.0     Business      Refunded

[5500 rows x 4 columns]

In [78]:
# Fill null Age using forward fill. 

df['Age'] = df['Age'].backfill()

C:\Users\pyugp\AppData\Local\Temp\ipykernel_14116\3464726884.py:3: FutureWarning: DataFrame.backfill/Series.backfill is deprecated. Use DataFrame.bfill/Series.bfill instead
  df['Age'] = df['Age'].backfill()

In [79]:
# Fill null SeatClass using mode. 

df['SeatClass'] = df['SeatClass'].mode()

In [80]:
# .Create indicator column for missing MobileNo. 
df['MobileNo_Missing'] = df['MobileNo'].isnull()

In [85]:
# Count rows having multiple missing values.
count = (df.isnull().sum(axis=1) > 1).sum()
count

np.int64(2187)

In [82]:
# Display top 20 rows containing maximum missing values. 
(df.isnull().sum(axis=1) > 3).sum()

np.int64(51)

In [83]:
# Create missing value summary table
missing_summary = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Percentage': df.isnull().mean() * 100
})

missing_summary

                    Missing Values  Percentage
BookingID                        0    0.000000
BookingDate                      0    0.000000
CustomerID                       0    0.000000
CustomerName                   934   16.981818
Gender                           0    0.000000
Age                              0    0.000000
MobileNo                         0    0.000000
EmailID                        535    9.727273
City                           226    4.109091
Country                          0    0.000000
FlightID                         0    0.000000
FlightName                       0    0.000000
FlightNumber                     0    0.000000
SourceCity                       0    0.000000
SourceAirport                    0    0.000000
DestinationCity                  0    0.000000
DestinationAirport               0    0.000000
FlightDate                       0    0.000000
DepartureTime                    0    0.000000
ArrivalTime                      0    0.000000
SeatClass                     5499   99.981818
SeatNumber                       0    0.000000
PNRNumber                      223    4.054545
TicketPrice                      0    0.000000
TaxAmount                        0    0.000000
TotalAmount                      0    0.000000
PaymentMode                      0    0.000000
PaymentStatus                  556   10.109091
BookingStatus                  224    4.072727
MobileNo_Missing                 0    0.000000

In [84]:
original_df = df.copy()
numeric_cols = df.select_dtypes(include="number").columns

df[numeric_cols] = df[numeric_cols].fillna(
    df[numeric_cols].mean()
)
comparison = pd.DataFrame({
    "Before": original_df.isnull().sum(),
    "After": df.isnull().sum()
})

comparison

                    Before  After
BookingID                0      0
BookingDate              0      0
CustomerID               0      0
CustomerName           934    934
Gender                   0      0
Age                      0      0
MobileNo                 0      0
EmailID                535    535
City                   226    226
Country                  0      0
FlightID                 0      0
FlightName               0      0
FlightNumber             0      0
SourceCity               0      0
SourceAirport            0      0
DestinationCity          0      0
DestinationAirport       0      0
FlightDate               0      0
DepartureTime            0      0
ArrivalTime              0      0
SeatClass             5499   5499
SeatNumber               0      0
PNRNumber              223    223
TicketPrice              0      0
TaxAmount                0      0
TotalAmount              0      0
PaymentMode              0      0
PaymentStatus          556    556
BookingStatus          224    224
MobileNo_Missing         0      0